<font size=4 face='楷体'>

## Python 中的异常捕获

最开始使用 Python 中异常捕获，就是简单的 try - except. 之后才渐渐有开始用 else/finally, 但是刚开始用的时候会记混 else/finally 的调用顺序  
写这部分的时候其实已经不会用错，算是个总结和备忘吧

### try - except

- 用 try/except 写一下

  ```python
  try:
      a = 1
      print(1)
      a = b
      print(a)
  except:
      print("Error")

  print("Finaly")
  ```

- 打印结果：

  > 1
  > Error
  > Finaly

- 结论：
  1. 先执行 try block, 直到发现了错误，不再执行异常之后的代码。
  2. 执行 except block.
  3. 向下继续。

### try - except - except ...

- 捕获多个异常
  ```python
  try:
      a = b
      print(a)
  except SyntaxError:
      print("SyntaxError")
  except NameError:
      print("NameError")
  ```
- 打印结果：

  > NameError

  可见，当 try 代码块执行出现异常，在 except 中匹配到了 NameError 的异常，则执行了对应 except 的语句。

- 结论：
  1. try 后可以捕获多个异常
  2. 匹配到异常后，try block 后续代码不会继续执行
  3. 没有匹配的异常时，仍然会抛出异常

### try - except - else

- 两个栗子：
  - a.
    ```python
    try:
        a = b
        print(a)
    except SyntaxError:
        print("SyntaxError")
    except NameError:
        print("NameError")
    else:
        print("OK")
    ```
  - b.
    ```python
    try:
        b = 1
        a = b
        print(a)
    except SyntaxError:
        print("SyntaxError")
    except NameError:
        print("NameError")
    else:
        print("OK")
    ```
- 打印结果：

  - a.
    > NameError
  - b.
    > OK

- 结论：
  - a 中 try block 抛出异常，并被捕获，执行 except block
  - b 中无异常，执行 else block

### try - except - finally

- 栗子：

  ```python
  try:
      a = b
      print(a)
  except SyntaxError:
      print("SyntaxError")
  except NameError:
      print("NameError")
  finally:
      print("Finally")
  ```

- 打印结果：

  > NameError
  > Finally

- 结论：
  - 无论 try block 是否抛出异常，finally block 都会执行
  - 执行顺序：
    - 如果 try block 未抛出异常，执行 finally block
    - 如果异常被捕获，先执行 except block, 再执行 finally block
    - 如果异常未被捕获，先执行 finally block，再抛出异常

### try - except - else - finally

- 栗子：
  - a. 异常
    ```python
    try:
        # b = 1
        a = b
        print(a)
    except SyntaxError:
        print("SyntaxError")
    except NameError:
        print("NameError")
    else:
        print("Ok")
    finally:
        print("Finally")
    ```
  - b. 未有异常
    ```python
    try:
        b = 1
        a = b
        print(a)
    except SyntaxError:
        print("SyntaxError")
    except NameError:
        print("NameError")
    else:
        print("Ok")
    finally:
        print("Finally")
    ```
- 打印结果：

  - a.
    > NameError
    > Finally
  - b.
    > 1
    > OK
    > Finally

- 结论：
  - 执行顺序：
    - 如果 try block 未抛出异常，先执行 else block, 再 finally block
    - 如果异常被捕获，先执行 except block, 再执行 finally block
    - 如果异常未被捕获，先执行 finally block，再抛出异常

### python 中异常捕获的效率

公司后端同学表示死活不用 try, 对效率影响大  
如果效率影响那么大的话，python 中的异常捕获能拿来做什么呢；后端同学又如何做异常处理呢。  
不理解，**待填坑**

[这里](https://www.jb51.net/article/134735.htm)有一遍对异常捕获性能的测试

## Reference

[python try 语句相关(try/except/else/finally)](https://blog.csdn.net/m0_37822685/article/details/80259402)

**2019.8.9**
